name: CI

on:
  push:
    branches: [ main ]
env: 
  BUCKET: reactdeployfmb
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Install dependencies
      run: yarn install
      
    - name: Build
      run: yarn build
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: Upload file to bucket
      run: gsutil -m rsync -R ./build gs://"$BUCKET"
      
    - name: Set Cache-Control
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"$BUCKET"/**/*.{png,css,js}

    - name: Set Cache-Control no Index no
      run: gsutil setmeta -h "Cache-Control:no-cache, no-store" gs://"$BUCKET"/index.html      
    
